#!/usr/bin/env python3
from pathlib import Path

BIN_PATH = Path(__file__).with_name('void')
if not BIN_PATH.exists():
    # fallback for this sandbox/upload name
    BIN_PATH = Path('/mnt/data/void(1)')

blob = BIN_PATH.read_bytes()
MASK64 = (1 << 64) - 1

def xs64(x: int) -> int:
    x ^= (x << 13) & MASK64
    x ^= x >> 7
    x ^= (x << 17) & MASK64
    return x & MASK64

def shuffle(n: int, seed: int) -> bytes:
    a = list(range(n))
    s = seed & MASK64
    for i in range(n, 1, -1):
        s = xs64(s)
        j = s % i
        a[i - 1], a[j] = a[j], a[i - 1]
    return bytes(a)

def gf_tables():
    exp = [0] * 512
    log = [0] * 256
    x = 1
    for i in range(255):
        exp[i] = x
        log[x] = i
        y = x << 1
        if x & 0x80:
            y ^= 0x1D
        x = y & 0xFF
    for i in range(512 - 255):
        exp[255 + i] = exp[i]
    return exp, log

EXP, LOG = gf_tables()

def gmul(a: int, b: int) -> int:
    if a == 0 or b == 0:
        return 0
    return EXP[LOG[a] + LOG[b]]

def ginv(a: int) -> int:
    return EXP[255 - LOG[a]]

sbox = shuffle(256, 0x9E3779B97F4A7C15)
inv_sbox = [0] * 256
for i, b in enumerate(sbox):
    inv_sbox[b] = i

pbox = shuffle(32, 0xD1B54A32D192ED03)
# matrix: inv(row ^ col) for row=0..3, col=4..7
mat = bytes(ginv(r ^ c) for r in range(4) for c in range(4, 8))

def invert_matrix(m: bytes) -> bytes:
    a = [[m[4*r+c] for c in range(4)] + [1 if r == c else 0 for c in range(4)] for r in range(4)]
    for col in range(4):
        pivot = next(r for r in range(col, 4) if a[r][col])
        a[col], a[pivot] = a[pivot], a[col]
        invp = ginv(a[col][col])
        for c in range(8):
            a[col][c] = gmul(a[col][c], invp)
        for r in range(4):
            if r == col:
                continue
            f = a[r][col]
            if f:
                for c in range(8):
                    a[r][c] ^= gmul(f, a[col][c])
    return bytes(a[r][4+c] for r in range(4) for c in range(4))

inv_mat = invert_matrix(mat)

# Round keys are generated by xorshift64 bytes at runtime, 3 * 32 bytes.
s = 0xA24BAED4963EE407
keys = []
for _ in range(96):
    s = xs64(s)
    keys.append(s & 0xFF)
keys = bytes(keys)

def xor_key(state: bytes, rnd: int) -> bytes:
    k = keys[32*rnd:32*(rnd+1)]
    return bytes(x ^ y for x, y in zip(state, k))

def inv_mix(state: bytes) -> bytes:
    out = bytearray(32)
    for off in range(0, 32, 4):
        block = state[off:off+4]
        for r in range(4):
            out[off+r] = 0
            for c in range(4):
                out[off+r] ^= gmul(inv_mat[4*r+c], block[c])
    return bytes(out)

def inv_perm(state: bytes) -> bytes:
    old = bytearray(32)
    for i, p in enumerate(pbox):
        old[p] = state[i]
    return bytes(old)

def inv_sub(state: bytes) -> bytes:
    return bytes(inv_sbox[b] for b in state)

# Final target bytes from .rodata at VA/file offset 0x2f80.
state = blob[0x2F80:0x2FA0]
for rnd in (2, 1, 0):
    state = xor_key(state, rnd)
    state = inv_mix(state)
    state = inv_perm(state)
    state = inv_sub(state)

flag = b'0xV01D{' + state + b'}'
print(flag.decode())

